export const techStacks = {
  Frontend: [
    "React",
    "React Native",
    "NextJS",
    "Angular",
    "Bootstrap",
    "Tailwind CSS",
    "Material UI",
    "Playwright",
    "Cypress",
    "Jest",
    "Selenium",
    "React Query",
    "Redux",
    "Zustand",
  ],
  Backend: [
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Scala",
    "Node.js",
    "tRPC",
    "Spring Boot",
    "GraphQL",
    "Snowflake",
    "Express.js",
    "Spark",
    "Firestore",
    "Pytest",
    "Junit",
    "Cucumber",
    "Mongoose",
  ],
  "Dev Tools & OS": [
    "Azure",
    "AWS",
    "GCP",
    "Firebase",
    "Figma",
    "Vercel",
    "Expo",
    "Bash",
    "Powershell",
    "Docker",
    "Git",
    "Github",
    "MailHog",
    "Data Dog",
    "Config Cat",
    "Twilio",
    "Sendgrid",
    "Sendo",
    "Kafka",
    "CircleCI",
    "Github Actions",
    "Postman",
    "Jira",
    "Confluence",
    "Slack",
    "Teams",
  ],
};
